CI: Test test result xml for success

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -65,19 +65,15 @@ variables:
         -testPlatform $TEST_PLATFORM \
         -testResults $(pwd)/$TEST_PLATFORM-results.xml \
         -logFile \
-        -batchmode
-    UNITY_EXIT_CODE=$?
-    if [ $UNITY_EXIT_CODE -eq 0 ]; then
+        -batchmode || true
+    UNITY_EXIT_CODE=$(sed -n 's/.*failed="\([^"]*\).*/\1/p' $(pwd)/$TEST_PLATFORM-results.xml | grep -m1 "")
+    if [ $UNITY_EXIT_CODE == "0" ]; then
       echo "Run succeeded, no failures occurred";
-    elif [ $UNITY_EXIT_CODE -eq 2 ]; then
-      echo "Run succeeded, some tests failed";
-    elif [ $UNITY_EXIT_CODE -eq 3 ]; then
-      echo "Run failure (other failure)";
+      exit 0
     else
-      echo "Unexpected exit code $UNITY_EXIT_CODE";
+      echo "$UNITY_EXIT_CODE tests failed.";
+      exit 1
     fi
-    cat $(pwd)/$TEST_PLATFORM-results.xml | grep test-run | grep Passed
-    exit $UNITY_TEST_EXIT_CODE
   artifacts:
     paths:
     - $(pwd)/$TEST_PLATFORM-results.xml
